version: '3.5'
services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: sgcdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
