version: '3.5'

services:
  sgcapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: sgc-app
    container_name: sgcapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/sgcapp
    env_file:
      - .env
    networks:
      - postgres
    # volumes:
    #   - ./:/var/www/sgcapp

  db:
    image: postgres:15.2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - postgres
    volumes:
      - ./postgres:/data/db

  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres


networks:
  postgres:
    driver: bridge