
import { Knex } from 'knex';
 
export async function up(knex: Knex): Promise<void> {
  return knex.raw(`


    CREATE TABLE users (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username varchar(25) NOT NULL,
      password varchar(100) NOT NULL,
      isActive boolean NOT NULL,
      roles roles NOT NULL,
    )
  `);
}
 
export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    DROP TABLE users
  `);
}