
import { Knex } from 'knex';
 
export async function up(knex: Knex): Promise<void> {
  return knex.raw(`

    CREATE TYPE roles AS ENUM('admin','user');

    CREATE TABLE users (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username varchar(25) NOT NULL,
      email varchar(50) NOT NULL,
      password varchar(50),
      roles roles
    )
  `);
}
 
export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    DROP TABLE users
  `);
}